### ISSUE TITLE
Bug: markers get deleted upon reopening playlist in Screen

### ISSUE THREAD

**Issue by gkertai** [videovillage/Screen-Issues#58] opened 2021-04-07 13:42 UTC
**Steps to reproduce:**
- create a playlist
- add markers to some clips
- save playlist - the `markers` nodes are present in the `.screenplaylist` JSON
- close Screen (or just ⌘W close the playlist)
- reopen the playlist either by double-clicking it or using the *Open Recent* function in Screen

**Expected behavior:** previously added markers should be visible

**What happens instead:** no markers can be seen on any playlist item, and if the playlist is saved, all `markers` nodes get removed from the JSON

Screen version 1.5.5 (2989)

**Comment by gregcotten** [comment] 2021-04-07 19:31
Hmmm I cannot reproduce this one - are the files possibly on a network drive or some non Mac formatted drive? I'm 99% confident that shouldn't matter, just checking all my bases here.

**Comment by gkertai** [comment] 2021-04-07 20:27
Upon further investigation, the entire `moviePreferences` node gets reset, including any sizing/playback/inspection/etc. settings.

Yes, my footage was on an exFAT formatted volume. I just tested on a single-item playlist referencing my Desktop (on an APFS volume), and the problem persists.

I am on macOS Mojave 10.14.6 (18G8022) in case that makes any difference.

Do please let me know how I can further assist your debugging efforts.

**Comment by gkertai** [comment] 2021-04-07 20:44
Following that hunch, since we've recently had a daylight saving time change, I tried to test if the issue can be reproduced with the system clock wound back a month. Unfortunately Screen either refused to start due to licensing issues, or refused to load files if it was already running. So there.

**Comment by gkertai** [comment] 2021-04-07 22:53
Not a regression. I tested versions all the way back to 1.2.1 and I can reproduce it on each.

**Comment by gregcotten** [comment] 2021-04-08 16:49
OK this is fixed and will be in 1.5.6 (uploading now)

**Closed** 2021-04-08 16:49 UTC

**Comment by gkertai** [comment] 2021-04-08 19:06
Thank you for the quick turnaround! Upgraded, tested, works well.
